<?php

namespace App\Services;

use App\Models\AppSetting;
use App\Models\DatabaseBackup;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use RuntimeException;

class DatabaseBackupService
{
    private string $disk = 'local';

    public function create(): DatabaseBackup
    {
        $connection = config('database.default');
        $sql = $this->dump($connection);
        $encrypted = Crypt::encryptString($sql);
        $filename = 'backup-'.$connection.'-'.now()->format('Ymd-His').'.sql.enc';
        $path = 'backups/database/'.$filename;

        Storage::disk($this->disk)->put($path, $encrypted);

        $backup = DatabaseBackup::create([
            'user_id' => Auth::id(),
            'filename' => $filename,
            'disk' => $this->disk,
            'path' => $path,
            'size' => Storage::disk($this->disk)->size($path) ?: 0,
            'connection' => $connection,
            'status' => 'completed',
            'notes' => 'Encrypted SQL dump generated by application.',
            'encrypted_at' => now(),
        ]);

        $this->prune();

        return $backup;
    }

    public function decryptedContent(DatabaseBackup $backup): string
    {
        if (! Storage::disk($backup->disk)->exists($backup->path)) {
            throw new RuntimeException('File backup tidak ditemukan.');
        }

        return Crypt::decryptString(Storage::disk($backup->disk)->get($backup->path));
    }

    public function delete(DatabaseBackup $backup): void
    {
        Storage::disk($backup->disk)->delete($backup->path);
        $backup->delete();
    }

    public function inspect(DatabaseBackup $backup): array
    {
        $sql = $this->decryptedContent($backup);
        $statements = $this->splitSqlStatements($sql);

        return [
            'filename' => $backup->filename,
            'connection' => $backup->connection,
            'statements' => count($statements),
            'drop_tables' => collect($statements)->filter(fn (string $statement) => str_starts_with(strtoupper(trim($statement)), 'DROP TABLE'))->count(),
            'create_tables' => collect($statements)->filter(fn (string $statement) => str_starts_with(strtoupper(trim($statement)), 'CREATE TABLE'))->count(),
            'insert_rows' => collect($statements)->filter(fn (string $statement) => str_starts_with(strtoupper(trim($statement)), 'INSERT INTO'))->count(),
            'size' => strlen($sql),
            'valid' => str_contains($sql, '-- Starterkit encrypted database backup'),
        ];
    }

    public function restore(DatabaseBackup $backup): array
    {
        $inspection = $this->inspect($backup);

        if (! $inspection['valid']) {
            throw new RuntimeException('Format backup tidak valid untuk aplikasi ini.');
        }

        $statements = $this->splitSqlStatements($this->decryptedContent($backup));
        $driver = DB::connection()->getDriverName();

        if (in_array($driver, ['mysql', 'mariadb'], true)) {
            DB::statement('SET FOREIGN_KEY_CHECKS=0');
        } elseif ($driver === 'sqlite') {
            DB::statement('PRAGMA foreign_keys = OFF');
        }

        try {
            foreach ($statements as $statement) {
                DB::unprepared($statement);
            }
        } finally {
            if (in_array($driver, ['mysql', 'mariadb'], true)) {
                DB::statement('SET FOREIGN_KEY_CHECKS=1');
            } elseif ($driver === 'sqlite') {
                DB::statement('PRAGMA foreign_keys = ON');
            }
        }

        return $inspection;
    }

    private function dump(string $connection): string
    {
        $driver = DB::connection($connection)->getDriverName();

        return match ($driver) {
            'mysql', 'mariadb' => $this->dumpMysql(),
            'sqlite' => $this->dumpSqlite(),
            default => throw new RuntimeException('Backup database belum mendukung driver '.$driver.'.'),
        };
    }

    private function dumpMysql(): string
    {
        $database = DB::connection()->getDatabaseName();
        $tables = collect(DB::select('SHOW FULL TABLES WHERE Table_type = "BASE TABLE"'))
            ->map(fn ($row) => array_values((array) $row)[0]);

        $output = $this->header('mysql', $database);

        foreach ($tables as $table) {
            $create = DB::selectOne('SHOW CREATE TABLE `'.$table.'`');
            $createSql = (array) $create;
            $output .= "\n\nDROP TABLE IF EXISTS `{$table}`;\n";
            $output .= array_values($createSql)[1].";\n\n";

            DB::table($table)->orderByRaw('1')->chunk(500, function ($rows) use (&$output, $table) {
                foreach ($rows as $row) {
                    $values = collect((array) $row)
                        ->map(fn ($value) => $value === null ? 'NULL' : DB::connection()->getPdo()->quote((string) $value))
                        ->implode(', ');
                    $columns = collect(array_keys((array) $row))
                        ->map(fn ($column) => '`'.$column.'`')
                        ->implode(', ');
                    $output .= "INSERT INTO `{$table}` ({$columns}) VALUES ({$values});\n";
                }
            });
        }

        return $output;
    }

    private function dumpSqlite(): string
    {
        $database = DB::connection()->getDatabaseName();
        $tables = collect(DB::select("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"))
            ->pluck('name');

        $output = $this->header('sqlite', $database);

        foreach ($tables as $table) {
            $schema = DB::selectOne("SELECT sql FROM sqlite_master WHERE type='table' AND name = ?", [$table]);
            $output .= "\n\nDROP TABLE IF EXISTS \"{$table}\";\n";
            $output .= $schema->sql.";\n\n";

            DB::table($table)->orderByRaw('1')->chunk(500, function ($rows) use (&$output, $table) {
                foreach ($rows as $row) {
                    $values = collect((array) $row)
                        ->map(fn ($value) => $value === null ? 'NULL' : DB::connection()->getPdo()->quote((string) $value))
                        ->implode(', ');
                    $columns = collect(array_keys((array) $row))
                        ->map(fn ($column) => '"'.$column.'"')
                        ->implode(', ');
                    $output .= "INSERT INTO \"{$table}\" ({$columns}) VALUES ({$values});\n";
                }
            });
        }

        return $output;
    }

    private function header(string $driver, string $database): string
    {
        return implode("\n", [
            '-- Starterkit encrypted database backup',
            '-- Driver: '.$driver,
            '-- Database: '.$database,
            '-- Generated at: '.now()->toDateTimeString(),
            '',
        ]);
    }

    private function splitSqlStatements(string $sql): array
    {
        $sql = collect(preg_split('/\R/', $sql) ?: [])
            ->reject(fn (string $line) => str_starts_with(trim($line), '--'))
            ->implode("\n");

        $statements = [];
        $buffer = '';
        $inSingleQuote = false;
        $inDoubleQuote = false;
        $escaped = false;
        $length = strlen($sql);

        for ($i = 0; $i < $length; $i++) {
            $char = $sql[$i];
            $buffer .= $char;

            if ($escaped) {
                $escaped = false;
                continue;
            }

            if ($char === '\\') {
                $escaped = true;
                continue;
            }

            if ($char === "'" && ! $inDoubleQuote) {
                $inSingleQuote = ! $inSingleQuote;
                continue;
            }

            if ($char === '"' && ! $inSingleQuote) {
                $inDoubleQuote = ! $inDoubleQuote;
                continue;
            }

            if ($char === ';' && ! $inSingleQuote && ! $inDoubleQuote) {
                $statement = trim($buffer);
                if ($statement !== '' && ! str_starts_with($statement, '--')) {
                    $statements[] = $statement;
                }
                $buffer = '';
            }
        }

        $tail = trim($buffer);
        if ($tail !== '' && ! str_starts_with($tail, '--')) {
            $statements[] = $tail;
        }

        return $statements;
    }

    private function prune(): void
    {
        $retention = max((int) AppSetting::getValue('backup_retention_days', '7'), 1);
        $cutoff = now()->subDays($retention);

        DatabaseBackup::where('created_at', '<', $cutoff)->each(fn (DatabaseBackup $backup) => $this->delete($backup));

        DatabaseBackup::latest()
            ->skip(20)
            ->take(PHP_INT_MAX)
            ->get()
            ->each(fn (DatabaseBackup $backup) => $this->delete($backup));
    }
}
